# TODO: Add replicas in the future
# Add strategy for each server as well
services:
  - name: server1
    address: 127.0.0.1:8081
    strategy: round_robin
    replicas:
      - address: 127.0.0.1:80812
  - name: server2
    address: 127.0.0.1:8082
    strategy: round_robin
    replicas:
      - address: 127.0.0.1:80822
  - name: server3
    address: 127.0.0.1:8083
    strategy: round_robin
    replicas:
      - address: 127.0.0.1:80832
  - name: server4
    address: 127.0.0.1:8084
    strategy: round_robin
    replicas:
      - address: 127.0.0.1:80842

